const GIT_LANG = "GIT_LANG"
const WIN_SIZE = "WIN_SIZE"

const MOBILE_SIZE = "MOBILE_SIZE"
const PC_SIZE = "PC_SIZE"
const TABLET_SIZE = "TABLET_SIZE"
const MODAL_BTN = "MODAL_BTN"
const TIMELINE = "TIMELINE"

const PROJECT_TYPE = "PROJECT_TYPE"
const LOCATION_TYPE = "LOCATION_TYPE"

export { GIT_LANG, WIN_SIZE, MOBILE_SIZE, PC_SIZE, TABLET_SIZE, MODAL_BTN, TIMELINE, PROJECT_TYPE, LOCATION_TYPE }
